### ISSUE TITLE
hi！may I ask if the latest version of Dayz can be used? 

### ISSUE THREAD

**Issue by momentdiedie** [Enoz/dma-dayz-cpp#10]
Hello, may I ask if the latest version of Dayz can be used? I don't seem to have seen the exe startup program. Has the latest offset been modified?

**Comment by momentdiedie** [comment]
I downloaded it but couldn't find the exe startup. I don't know how to use it. I know how to use DMA, but I don't know how to use your project

**Comment by Enoz** [comment]
This project is no longer maintained, so the offsets are likely not updated. The object structure in DayZ rarely changes, so you are likely able to continue using this if you just update the offsets. They are usually shared on UC after an update, so check there if you are unable to get the offsets yourself.

**Comment by momentdiedie** [comment]
Thanks
