### ISSUE TITLE
Radar not opening

### ISSUE THREAD

**Issue by Vlieker** [Enoz/dma-dayz-cpp#11]
Good evening,

Awesome work! The overlay is working perfect :) Though there seems to be an issue with the radar not popping up when starting it... When debugging it seems everything is working fine, except the radar does not seem to open when starting it.

**Comment by Enoz** [comment]
You very likely don't have the maps images downloaded

**Comment by Vlieker** [comment]
Would it be possible to have this issue removed? Thanks :)
