### ISSUE TITLE
Hello, author.

### ISSUE THREAD

**Issue by a27381** [Enoz/dma-dayz-cpp#4]
Hello, thank you for providing such a useful tool. I have some questions and hope you can help. In the game, the radar on the right side shows no reaction and no information, only a map. Could you please add some information on the map? Thank you. 

(Note: The translation may vary slightly based on context or specific game-related terms.)

**Comment by GoSSy4691** [comment]
Hi
Can you show example. What kind of "information" ? 
If it's sensitive thing you can write me on my email (on my personal github page)
